apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wnk1a3yxp-nodejs
  janus-idp.io/tekton: wnk1a3yxp-nodejs
  backstage.io/kubernetes-id: wnk1a3yxp-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wnk1a3yxp-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
