apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wnk1a3yxp-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wnk1a3yxp-nodejs 
  name: wnk1a3yxp-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: wnk1a3yxp-nodejs 
