apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: wnk1a3yxp-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-68185016d1.sw09.p3.openshiftapps.com/rhtap/rhtap-qe-nodejs:d95056c85542d23158a54a695f4a75e657b777e7@sha256:486e6c056708668eaeb528ea60069b8d0ba7178b8bc4da69246b471dd96bd826
          name: container-image
